---
.catalog:
  name: "elk"
  version: "5.6.7-0"
  description: "Log Monitoring Stack"
  questions:
    - variable: "logstash_inputs"
      description: |
        Logstash inputs. These will be added to input { } section
        of logstash.conf
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: |
        tcp {
          port => "5000"
          codec => "json"
        }
    - variable: "logstash_filters"
      description: |
        Logstash filters. These will be added to filter { } section
        of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: false
      default: ""
    - variable: "logstash_outputs"
      description: |
        Logstash outputs. These will be added to output { } section
        of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
    - variable: "cluster_name"
      type: "string"
      required: true
      label: "Cluster name"
      description: "Name of the Elasticsearch Cluster"
      default: "elk-cluster"
    - variable: "es_heap_size"
      type: "string"
      required: true
      label: "Heap size"
      description: "Heap size to be allocated for Java (elastic nodes)"
      default: "1g"
    - variable: "es_mem_limit"
      type: "int"
      required: true
      label: "Memory limit in byte (elastic nodes)"
      description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (data nodes)"
      default: 2147483648
    - variable: "initial_es_nodes"
      label: "Elasticsearch nodes"
      type: "int"
      required: true
      default: 2

es-master:
  scale: ${initial_es_nodes}
es-data:
  scale: ${initial_es_nodes}
es-client:
  scale: ${initial_es_nodes}

logstash:
  metadata:
    logstash:
      inputs: |
        ${logstash_inputs}
      filters: |
        ${logstash_filters}
      outputs: |
        ${logstash_outputs}

lb:
  start_on_create: true
  lb_config:
    certs: []
    default_cert:
    port_rules:
    - priority: 1
      protocol: tcp
      service: logstash
      source_port: 5000
      target_port: 5000
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    strategy: recreate
    interval: 2000
