---
version: '2'

volumes:
  es-data:
    per_container: true
    driver: rancher-nfs

services:
  silo:
    image: docker.elastic.co/elasticsearch/elasticsearch:${elk_version}
    volumes:
    - es-data:/usr/share/elasticsearch/data
    environment:
      - "cluster.name=${cluster_name}"
      - "node.name=$${HOSTNAME}"
      - "node.attr.stack=elk-data-temp"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xms${es_heap_size} -Xmx${es_heap_size}"
      - "node.master=true"
      - "node.data=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${es_mem_limit}
    mem_swappiness: 0
    cap_add:
      - IPC_LOCK
    external_links:
      - ${external_link}:elasticsearch
    labels:
      io.rancher.sidekicks: sysctl
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name} # one per host (soft)

  sysctl:
    image: rawmind/alpine-sysctl:0.1
    network_mode: none
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=262144"
    labels:
      io.rancher.container.start_once: true

