---
.catalog:
  name: "elk-data-temp"
  version: "1.0.0"
  description: "ELK Elasticsearch Cluster"
  questions:
    - variable: "elk_version"
      type: "string"
      required: true
      label: "ELK image version"
      default: "5.6.7"
    - variable: "cluster_name"
      type: "string"
      required: true
      label: "Cluster name"
      description: "Name of the Elasticsearch Cluster"
      default: "elk-cluster"
    - variable: "external_link"
      type: "string"
      required: true
      label: "stack/service name"
      description: "<stack>/<service> name to link to your master Elasticsearch stack and service"
      default: "elk-data/elasticsearch"
    - variable: "es_heap_size"
      type: "string"
      required: true
      label: "Heap size"
      description: "Heap size to be allocated for Java (elastic nodes)"
      default: "1g"
    - variable: "es_mem_limit"
      type: "int"
      required: true
      label: "Memory limit in byte (elastic nodes)"
      description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (data nodes)"
      default: 2147483648
    - variable: "initial_es_nodes"
      label: "Elasticsearch nodes"
      type: "int"
      required: true
      default: 2
silo:
  scale: ${initial_es_nodes}
