---
.catalog:
  name: "elk-data"
  version: "6.2.0-0"
  description: "ELK Elasticsearch Cluster"
  questions:
    - variable: "cluster_name"
      type: "string"
      required: true
      label: "Cluster name"
      description: "Name of the Elasticsearch Cluster"
      default: "elk-cluster"
    - variable: "es_heap_size"
      type: "string"
      required: true
      label: "Heap size"
      description: "Heap size to be allocated for Java (elastic nodes)"
      default: "1g"
    - variable: "es_mem_limit"
      type: "int"
      required: true
      label: "Memory limit in byte (elastic nodes)"
      description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (data nodes)"
      default: 2147483648
    - variable: "initial_es_masters"
      label: "Elasticsearch Master nodes"
      type: "int"
      required: true
      default: 2
    - variable: "initial_es_datas"
      label: "Elasticsearch Data nodes"
      type: "int"
      required: true
      default: 3
    - variable: "initial_es_clients"
      label: "Elasticsearch Client nodes"
      type: "int"
      required: true
      default: 2
master:
  scale: ${initial_es_masters}
data:
  scale: ${initial_es_datas}
client:
  scale: ${initial_es_clients}
