---
.catalog:
  name: "elk"
  version: "1.0.0"
  description: "Log Monitoring Stack"
  questions:
    - variable: "elk_version"
      type: "string"
      required: true
      label: "ELK image version"
      default: "5.5.2"
    - variable: "cluster_name"
      type: "string"
      required: true
      label: "Cluster name"
      description: "Name of the Elasticsearch Cluster"
      default: "elk-cluster"

logstash-logspout:
  metadata:
    logstash:
      inputs: |
        tcp {
          port => "5000"
          codec => "json"
        }
      filters: ""
      outputs: |
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => [ "logstash-%{+YYYY.MM.dd}" ]
        }

logstash-syslog:
  metadata:
    logstash:
      inputs: |
        tcp {
          port => "5514"
          proxy_protocol => true
        }
      filters: ""
      outputs: |
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => [ "syslog-%{+YYYY.MM.dd}" ]
        }
lb:
  start_on_create: true
  lb_config:
    certs: []
    default_cert:
    port_rules:
    - priority: 1
      protocol: tcp
      service: logstash-logspout
      source_port: 5000
      target_port: 5000
    - priority: 1
      protocol: tcp
      service: logstash-syslog
      source_port: 5514
      target_port: 5514
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    strategy: recreate
    interval: 2000
